---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Booking
  labels:
    app: Booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Booking
  template:
    metadata:
      labels:
        app: Booking
    spec:
      containers:
        - name: Booking
          image: username/Booking:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Payment
  labels:
    app: Payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Payment
  template:
    metadata:
      labels:
        app: Payment
    spec:
      containers:
        - name: Payment
          image: username/Payment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Exhibition
  labels:
    app: Exhibition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Exhibition
  template:
    metadata:
      labels:
        app: Exhibition
    spec:
      containers:
        - name: Exhibition
          image: username/Exhibition:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Booking
  labels:
    app: Booking
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Booking


---


apiVersion: v1
kind: Service
metadata:
  name: Payment
  labels:
    app: Payment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Payment


---


apiVersion: v1
kind: Service
metadata:
  name: Exhibition
  labels:
    app: Exhibition
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Exhibition

